- name: configuring mysql server 
  hosts: local
  connection: local
  become: yes 
  tasks:
  - name: installing mysql server 
    ansible.builtin.package:
      name: mysql-server 
      state: installed 

  - name: start and enable mysql server 
    ansible.builtin.service:
      name: mysqld 
      state: started
      enabled: yes 