- name: configuring mysql server 
  hosts: local
  connection: local
  become: yes 
  tasks:
  - name: installing mysql server 
    ansible.builtin.package:
      name: mysql-server 
      state: installed 